### ISSUE TITLE
Custom commands and interactive objects

### ISSUE THREAD

**Issue by katafrakt** [facundoolano/advenjure#1]
Hi! I really like this project (even though I almost don't know Clojure) and I had some fun using it already. However, there are two things I missed. Maybe the are already present, but I couldn't take that from example game:

1. Custom commands, i.e. `push button` or `pull lever` (maybe even `move desk`, but that's probably another story). They would for example open doors or simply print some messages.
2. Interactive object where player would need to provide some text from keyboard, for example PIN to ATM or password to the computer, based on some clues around. This could also be a dialog option (say password to a doorman etc.)

So, is it possible to achieve those with current state of engine? If not, do you perhaps have some roadmap on which they are :wink: ?

Anyway, thanks for your effort and publishing this project!

**Comment by CharlesHD** [comment]
That's a fun fact. Was about to post about the same thing about this engine.
Would love to define custom actions.

**Comment by facundoolano** [comment]
I'm sorry for the delayed answer, I just saw this (forgot to turn on the notifications for this project). I'm glad to see advenjure being used!

There are already mechanics to easily add custom actions (that is, actions that do nothing by default but execute the pre and post conditions, or print a message). What's missing is the ability for the library user to extend the verb map, so you can add those custom commands without having to change the source of the lib. I planned to add that at some point, and should be fairly straightforward, so let me take a look at it and get back at you.

In the meantime, if you have some sort of list of actions you'd like to see supported out of the box, do send them, I can add them right away and publish a new version of the lib.

**Comment by facundoolano** [comment]
About the other feature (interactive objects), it sounds interesting but would require a bit more effort to implement. I'm currently working on other open source projects so I'm not sure when I'll be able to start adding features to this one again. 

Although if I see there's people using this lib actively I'll definitely switch back to it as soon as I can.

**Comment by facundoolano** [comment]
Ok @katafrakt @CharlesHD the custom commands was a simple enough change. I've published a new advenjure version to clojars, now you can pass a [custom verb map](https://github.com/facundoolano/advenjure-example/blob/master/src/example/core.clj#L13) to `game/run`, with your own verb definitions.

In the example game you can see the [verb definitions](https://github.com/facundoolano/advenjure-example/blob/master/src/example/verbs.clj) and how to react with custom code through [post conditions](https://github.com/facundoolano/advenjure-example/blob/master/src/example/rooms.clj#L51). 

If you dig a bit on the source code of this repo, you can also see how to make fully functional verbs so you are not forced to put the custom logic in the pre/post conditions.

Closing this one, open a new issue if you have any other feature request.

**Comment by CharlesHD** [comment]
Cool ! I'm not going to use your library right now, but it's marked as a really promising one for a future project. 
Thanks for being that reactive !

**Comment by katafrakt** [comment]
Agreed. Thank you a lot! I will try that out.

**Comment by facundoolano** [comment]
Hey @katafrakt and @CharlesHD I've been doing more development on this project and finally added the user input feature you requested. 

There's a `prompt-value` function to do it, you can see it used [here](https://github.com/facundoolano/advenjure-example/blob/master/src/example/living.cljc#L30).

**Comment by katafrakt** [comment]
Thats just awesome! Thanks @facundoolano!

**Comment by CharlesHD** [comment]
Yeehee !
