### ISSUE TITLE
Cool idea but I can't change the font size!

### ISSUE THREAD

**Issue by feoh** [facundoolano/advenjure#3]
I'm partially blind and this font is tiny.

**Comment by facundoolano** [comment]
Hi! The web interface uses [jQuery Terminal](https://github.com/jcubic/jquery.terminal). You can see the [full CSS](https://github.com/facundoolano/advenjure-example/blob/master/resources/jquery.terminal-0.11.7.css) in the example game resources folder, and some modifications I've mad myself in the [HTML file](https://github.com/facundoolano/advenjure-example/blob/master/index.html#L23).

You can change the font size by updating the css as shown in that last link.
