### ISSUE TITLE
Potential feature request: game state events (that are not tied to dialogs)

### ISSUE THREAD

**Issue by rdpfeiffer** [facundoolano/advenjure#8]
I'm really enjoying creating a geocaching adventure app using this engine!

But I think I'm looking for a feature which doesn't currently exist. I want to write logic which depends on the state of the game. As a concrete example, the player should not be able to head to a new location ("room") until they have read a note with the coordinates written on it. I think that I could make this work using the events in the advenjure.dialogs namespace (such as set-event, event?, not-event?, etc), but I think that I would be abusing this feature, as it's specifically tied to dialogs.

Or am I just confused about the correct approach to doing this?

**Comment by facundoolano** [comment]
You can do that with events (events are nothing special actually, just a set in the game map), but not using those dialog helpers but with verb post/pre conditions. It would be something along the lines:

```clojure
;; add a postcondition to the read verb of the note item, to set an event
(defn after-read-note [oldgs gs] (update-in gs [:events] conj :note-read))
(def note (item/make "a note" "it has text in it" :read {:say "(note contents)" :post `after-read-note}))

;; conditionally allow to enter a room depending on the presence of the read note event
(defn has-read-note [gs]
  (if ((:events gs) :note-read)
    :my-room
    "I don't know the coordinates"))

(def room-map (-> {:some-room some-room
                   :my-room   my-room}
                  (room/one-way-connect :some-room :north `has-read-note)))
```

There may be some typos there, but that's the general idea. Take a look on the [example-game](https://github.com/facundoolano/advenjure-example) and [house-taken-over](https://github.com/facundoolano/house-taken-over) for examples on post/pre conditions and how to lock some locations depending on some condition.

**Comment by rdpfeiffer** [comment]
Beautiful! It all works like a charm.

I had everything figured out, except I hadn't zeroed in on the :post functionality yet. But now I have. :-)

Thanks for the quick help. I'm loving this! You can consider this newbie issue closed.

**Comment by facundoolano** [comment]
Great.
